language: objective-c
osx_image: xcode8.3
cache:
  bundler: true
  cocoapods: true
  directories:
    - ~/.rbenv
    - ~/.cocoapods
    - ~/Library/Caches/CocoaPods
    - .bundle
    - vendor
env:
  global:
    - PROJECT='MyApp' # project name
    - SDK="iphonesimulator10.3"
    - SCHEME="$PROJECT"
    - WORKSPACE="$PROJECT.xcworkspace"
    - DESTINATION="OS=10.3,name=iPhone 7"
    - CONFIGURATION='Debug'
install:
  - set -o pipefail
  - ./scripts/install
script:
  - export REPO_SLUG="$TRAVIS_REPO_SLUG"
  - export SRC_BRANCH="$(bash scripts/ci/src_branch)"
  - export PR_NUMBER="$(bash scripts/ci/pr_number)"
  - bash ./scripts/tests/pod
  - bash ./scripts/tests/app
  - bash ./scripts/tests/lint
notifications:
  email: false
after_success:
  # - ./scripts/ci/codecov $PROJECT
