#!/bin/bash

if [[ "$CI" != 'true' ]]; then
    echo 'Exporting build environment variables...'
    export SDK='iphonesimulator11.2'
    export SCHEME='MyApp'
    export WORKSPACE='MyApp.xcworkspace'
    export DESTINATION='OS=11.2,name=iPhone 7'
    export CONFIGURATION='Debug'
fi

rm -rf ./build

xcodebuild test \
    -workspace "$WORKSPACE" \
    -scheme "$SCHEME" \
    -sdk "$SDK" \
    -destination "$DESTINATION" \
    -derivedDataPath build \
    ONLY_ACTIVE_ARCH=YES \
    -configuration "$CONFIGURATION"

exit "${PIPESTATUS[0]}"
